/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/public/ship/shuttle2/classic.gltf 
Author: Microsoft (https://sketchfab.com/microsoft)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-shuttle-ff4b00b7ebb24fdd98fb96b08f2c43c9
Title: Space Shuttle
*/

import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export default function Model(props) {
  const { nodes, materials } = useLoader(
    GLTFLoader,
    "/src/public/ship/shuttle2/classic.gltf"
  );
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.Material__197}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.4}
      />
    </group>
  );
}
