/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/public/ship/shuttle3/premium.gltf 
Author: tramkar (https://sketchfab.com/tramkar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceship-torb-v2-832049eab0cf4342a24223d71bc9642c
Title: spaceship "torb" v2
*/

import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export default function Model(props) {
  const { nodes, materials } = useLoader(
    GLTFLoader,
    "/src/public/ship/shuttle3/premium.gltf"
  );
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group {...props} dispose={null}>
      <group
        position={[-21.131, -0.437, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[2.446, 0.87, 2.446]}
      >
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.main_paint}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.bright_light}
        />
      </group>
      <group
        position={[-15.048, -0.337, 5.251]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.682}
      >
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.main_paint}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.bright_light}
        />
      </group>
      <group
        position={[-3.437, -0.588, 4.998]}
        rotation={[0, 0, Math.PI / 2]}
        scale={0.682}
      >
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.main_paint}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.bright_light}
        />
      </group>
      <group
        position={[10.455, -0.534, 5.634]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.371}
      >
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.main_paint}
        />
        <mesh geometry={nodes.Object_21.geometry} material={materials.glass} />
      </group>
      <group
        position={[-9.109, -0.511, 5.004]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.35}
      >
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.main_paint}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[-5.038, -0.505, 5.641]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.494}
      >
        <mesh
          geometry={nodes.Object_34.geometry}
          material={materials.main_paint}
        />
        <mesh geometry={nodes.Object_35.geometry} material={materials.glass} />
      </group>
      <group
        position={[-18.18, -0.337, 4.393]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        scale={0.682}
      >
        <mesh
          geometry={nodes.Object_37.geometry}
          material={materials.main_paint}
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials.bright_light}
        />
      </group>
      <group
        position={[22.794, -0.454, 2.001]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.471}
      >
        <mesh
          geometry={nodes.Object_40.geometry}
          material={materials.main_paint}
        />
        <mesh
          geometry={nodes.Object_41.geometry}
          material={materials.bright_light}
        />
      </group>
      <group
        position={[-0.388, -0.472, 4.148]}
        rotation={[Math.PI / 2, 0, 0.063]}
        scale={0.394}
      >
        <mesh
          geometry={nodes.Object_45.geometry}
          material={materials.main_paint}
        />
        <mesh
          geometry={nodes.Object_46.geometry}
          material={materials.windows_glow}
        />
      </group>
      <group
        position={[-8.786, 2.705, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.114, 0.059, 0.273]}
      >
        <mesh
          geometry={nodes.Object_48.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Object_49.geometry}
          material={materials.windows_glow}
        />
        <mesh
          geometry={nodes.Object_50.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={nodes.Object_51.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={nodes.Object_52.geometry}
          material={materials["Material.009"]}
        />
      </group>
      <group
        position={[-9.796, 2.69, 0]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.467, 0.028, 0.467]}
      >
        <mesh
          geometry={nodes.Object_54.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          geometry={nodes.Object_55.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          geometry={nodes.Object_56.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          geometry={nodes.Object_57.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_58.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          geometry={nodes.Object_59.geometry}
          material={materials.windows_glow}
        />
        <mesh
          geometry={nodes.Object_60.geometry}
          material={materials.material_0}
        />
      </group>
      <group position={[0, 0, -0.047]}>
        <mesh
          geometry={nodes.Object_67.geometry}
          material={materials.main_paint}
        />
        <mesh
          geometry={nodes.Object_68.geometry}
          material={materials.main_paint}
        />
      </group>
      <group position={[8.851, -1.591, 4.541]} scale={[0.986, 0.568, 0.986]}>
        <mesh
          geometry={nodes.Object_70.geometry}
          material={materials.main_paint}
        />
        <mesh geometry={nodes.Object_71.geometry} material={materials.glass} />
        <mesh
          geometry={nodes.Object_72.geometry}
          material={materials.windows_glow}
        />
      </group>
      <group position={[8.851, -1.627, 5.198]} scale={[0.048, 0.028, 0.048]}>
        <mesh
          geometry={nodes.Object_74.geometry}
          material={materials.main_paint}
        />
        <mesh
          geometry={nodes.Object_75.geometry}
          material={materials.main_paint}
        />
      </group>
      <group position={[0, -0.093, -0.036]}>
        <mesh
          geometry={nodes.Object_77.geometry}
          material={materials.main_paint}
        />
        <mesh
          geometry={nodes.Object_78.geometry}
          material={materials.main_paint}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.main_paint}
      />
      <mesh geometry={nodes.Object_5.geometry} material={materials.glass} />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.bright_light}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.windows_glow}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.main_paint}
        position={[-8.031, 1.164, 2.462]}
        scale={[0.098, 0.138, 0.098]}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.main_paint}
        position={[-14.012, 0.429, 5.458]}
        rotation={[0.494, 0, 0]}
        scale={0.594}
      />
      <mesh
        geometry={nodes.Object_28.geometry}
        material={materials.main_paint}
        position={[-19.641, 2.186, 0]}
        scale={0.933}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.main_paint}
        position={[-19.641, -2.859, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.933}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.main_paint}
        position={[-14.092, -0.491, 6.237]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.494}
      />
      <mesh
        geometry={nodes.Object_43.geometry}
        material={materials.main_paint}
        position={[-19.557, 1.532, 1.851]}
        rotation={[0.634, 0, 0]}
        scale={0.938}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials.bright_light}
      />
      <mesh
        geometry={nodes.Object_64.geometry}
        material={materials.main_paint}
      />
      <mesh
        geometry={nodes.Object_65.geometry}
        material={materials.main_paint}
      />
      <mesh
        geometry={nodes.Object_80.geometry}
        material={materials["Material.003"]}
        position={[-9.128, 2.667, 0]}
        scale={1.439}
      />
      <mesh
        geometry={nodes.Object_82.geometry}
        material={materials["Material.003"]}
        position={[-8.193, 2.853, 0]}
        scale={0.634}
      />
      <mesh
        geometry={nodes.Object_84.geometry}
        material={materials.main_paint}
        position={[12.726, 1.515, 4.681]}
        rotation={[0.348, 0, 0]}
        scale={0.248}
      />
    </group>
  );
}
