/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/public/ship/shuttle3/test/premium.gltf 
Author: Rakshaan (https://sketchfab.com/rakshaan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/colony-tactical-ship-050dae751a404f3087aac9241958e2b1
Title: Colony Tactical Ship
*/

import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";

export default function Model(props) {
  const { nodes, materials } = useLoader(
    GLTFLoader,
    "/src/public/ship/shuttle3/premium.gltf"
  );

  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group {...props} dispose={null}>
      <ambientLight intensity={2} />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={22.4} position={(1, 5)}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.Hull_Chassis}
          />
          <mesh
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.Wing_Mount}
          />
          <mesh
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.Wing_Mount}
          />
          <mesh
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.Hull}
          />
          <mesh
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.Thruster_Swivel}
          />
          <mesh
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.Thruster_Swivel}
          />

          <mesh
            geometry={nodes.defaultMaterial_11.geometry}
            material={materials.Thruster_Components}
          />
          <mesh
            geometry={nodes.defaultMaterial_12.geometry}
            material={materials.Hull}
          />
          <mesh
            geometry={nodes.defaultMaterial_13.geometry}
            material={materials.Thruster_Components}
          />
          <mesh
            geometry={nodes.defaultMaterial_14.geometry}
            material={materials.Thruster_Swivel}
          />
          <mesh
            geometry={nodes.defaultMaterial_15.geometry}
            material={materials.Thruster_Swivel}
          />
          <mesh
            geometry={nodes.defaultMaterial_16.geometry}
            material={materials.Thruster_Components}
          />
          <mesh
            geometry={nodes.defaultMaterial_17.geometry}
            material={materials.Thruster_Components}
          />
          <mesh
            geometry={nodes.defaultMaterial_18.geometry}
            material={materials.Thruster_Components}
          />
          <mesh
            geometry={nodes.defaultMaterial_19.geometry}
            material={materials.Thruster_Components}
          />
          <mesh
            geometry={nodes.defaultMaterial_20.geometry}
            material={materials.Thruster_Swivel}
          />
          <mesh
            geometry={nodes.defaultMaterial_21.geometry}
            material={materials.Thruster_Swivel}
          />
          <mesh
            geometry={nodes.defaultMaterial_22.geometry}
            material={materials.Thruster_Components}
          />
          <mesh
            geometry={nodes.defaultMaterial_23.geometry}
            material={materials.Thruster_Components}
          />
          <mesh
            geometry={nodes.defaultMaterial_24.geometry}
            material={materials.Thruster_Swivel}
          />
          <mesh
            geometry={nodes.defaultMaterial_25.geometry}
            material={materials.Thruster_Swivel}
          />
          <mesh
            geometry={nodes.defaultMaterial_26.geometry}
            material={materials.Thruster_Components}
          />
          <mesh
            geometry={nodes.defaultMaterial_27.geometry}
            material={materials.Thruster_Swivel}
          />
          <mesh
            geometry={nodes.defaultMaterial_28.geometry}
            material={materials.Thruster_Swivel}
          />
          <mesh
            geometry={nodes.defaultMaterial_29.geometry}
            material={materials.Thruster_Swivel}
          />
          <mesh
            geometry={nodes.defaultMaterial_30.geometry}
            material={materials.Thruster_Swivel}
          />
          <mesh
            geometry={nodes.defaultMaterial_31.geometry}
            material={materials.Thruster_Components}
          />
        </group>
      </group>
    </group>
  );
}
